# Generated by Django 2.1.7 on 2019-02-20 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12, verbose_name='口令')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
        ),
    ]
