# Generated by Django 2.1.7 on 2019-02-23 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('link', models.CharField(max_length=500, verbose_name='链接')),
                ('imgUrl', models.CharField(blank=True, max_length=300, null=True, verbose_name='封面')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('isInvalid', models.BooleanField(default=False, verbose_name='是否失效')),
            ],
            options={
                'verbose_name': '书签',
                'verbose_name_plural': '书签',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('isEnable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '书签分类',
                'verbose_name_plural': '书签分类',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='账号')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
        ),
        migrations.AddField(
            model_name='sort',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Sort', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Users', verbose_name='用户'),
        ),
    ]
