# Generated by Django 2.1.7 on 2019-02-20 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('isEnable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '书签分类',
                'verbose_name_plural': '书签分类',
            },
        ),
    ]
