# Generated by Django 2.1.7 on 2019-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.EmailField(max_length=254, verbose_name='账号'),
        ),
    ]
