# Generated by Django 2.1.7 on 2019-02-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sort',
        ),
    ]
