# Generated by Django 2.1.7 on 2019-02-20 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('link', models.CharField(max_length=100, verbose_name='链接')),
                ('imgUrl', models.CharField(blank=True, max_length=300, null=True, verbose_name='封面')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('isInvalid', models.BooleanField(default=False, verbose_name='是否失效')),
                ('sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Sort', verbose_name='分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '书签',
                'verbose_name_plural': '书签',
            },
        ),
    ]
