# Generated by Django 2.1.7 on 2019-02-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='link',
            field=models.CharField(max_length=500, verbose_name='链接'),
        ),
    ]
